name = "playground"
# main = "./some-entrypoint"

type = "typescript"
account_id = "a8504cbbaac4bbc139151414bd1ee748"
workers_dev = true
route = ""
zone_id = "c3350b444dabecb4273f835d0b214914"
compatibility_date = "2022-04-07"

[site]
bucket = ".output/public"
entry-point = ".output"

[build]
command = ""
upload.format = "service-worker"
